
-- INSERT ON "CAJEROS" 10 TUPLES
INSERT INTO CAJEROS (NOMBRE_APELLIDOS) VALUES ("Maria O");
INSERT INTO CAJEROS (NOMBRE_APELLIDOS) VALUES ("Jose P");
INSERT INTO CAJEROS (NOMBRE_APELLIDOS) VALUES ("Enric A");
INSERT INTO CAJEROS (NOMBRE_APELLIDOS) VALUES ("Chema C");
INSERT INTO CAJEROS (NOMBRE_APELLIDOS) VALUES ("Santiago L");
INSERT INTO CAJEROS (NOMBRE_APELLIDOS) VALUES ("Eloisa D");
INSERT INTO CAJEROS (NOMBRE_APELLIDOS) VALUES ("Iryna P");
INSERT INTO CAJEROS (NOMBRE_APELLIDOS) VALUES ("Daniel P");
INSERT INTO CAJEROS (NOMBRE_APELLIDOS) VALUES ("Flurgencia F");
INSERT INTO CAJEROS (NOMBRE_APELLIDOS) VALUES ("Ingrid G");

-- INSERT ON "PRODUCTOS" 10 TUPLES
INSERT INTO PRODUCTOS (NOMBRE) VALUES ("Camiseta");
INSERT INTO PRODUCTOS (NOMBRE) VALUES ("Camiseta");
INSERT INTO PRODUCTOS (NOMBRE) VALUES ("Pantalon");
INSERT INTO PRODUCTOS (NOMBRE) VALUES ("Gorra");
INSERT INTO PRODUCTOS (NOMBRE) VALUES ("Calcetines");
INSERT INTO PRODUCTOS (NOMBRE) VALUES ("Guantes");
INSERT INTO PRODUCTOS (NOMBRE) VALUES ("Chaqueta");
INSERT INTO PRODUCTOS (NOMBRE) VALUES ("Fular");
INSERT INTO PRODUCTOS (NOMBRE) VALUES ("Albornoz");

-- INSERT ON "MAQUINAS_REGISTRADORAS" 10 TUPLES
INSERT INTO MAQUINAS_REGISTRADORAS (PISO) VALUES (1);
INSERT INTO MAQUINAS_REGISTRADORAS (PISO) VALUES (2);
INSERT INTO MAQUINAS_REGISTRADORAS (PISO) VALUES (3);
INSERT INTO MAQUINAS_REGISTRADORAS (PISO) VALUES (4);
INSERT INTO MAQUINAS_REGISTRADORAS (PISO) VALUES (5);
INSERT INTO MAQUINAS_REGISTRADORAS (PISO) VALUES (6);
INSERT INTO MAQUINAS_REGISTRADORAS (PISO) VALUES (7);
INSERT INTO MAQUINAS_REGISTRADORAS (PISO) VALUES (8);
INSERT INTO MAQUINAS_REGISTRADORAS (PISO) VALUES (9);
INSERT INTO MAQUINAS_REGISTRADORAS (PISO) VALUES (10);

-- INSERT ON "VENTA" 10 TUPLES
INSERT INTO VENTA (CAJERO, MAQUINA, PRODUCTO) VALUES (1, 1, 1);
INSERT INTO VENTA (CAJERO, MAQUINA, PRODUCTO) VALUES (2, 3, 1);
INSERT INTO VENTA (CAJERO, MAQUINA, PRODUCTO) VALUES (1, 2, 3);
INSERT INTO VENTA (CAJERO, MAQUINA, PRODUCTO) VALUES (6, 5, 1);
INSERT INTO VENTA (CAJERO, MAQUINA, PRODUCTO) VALUES (7, 1, 5);
INSERT INTO VENTA (CAJERO, MAQUINA, PRODUCTO) VALUES (4, 6, 9);
INSERT INTO VENTA (CAJERO, MAQUINA, PRODUCTO) VALUES (2, 10, 3);
INSERT INTO VENTA (CAJERO, MAQUINA, PRODUCTO) VALUES (4, 8, 5);
INSERT INTO VENTA (CAJERO, MAQUINA, PRODUCTO) VALUES (6, 7, 4);
INSERT INTO VENTA (CAJERO, MAQUINA, PRODUCTO) VALUES (1, 1, 1);