
-- INSERT EJERCICIO 1 UD15

/* INSERT TABLA DESPACHOS */
INSERT INTO DESPACHOS (NUMERO, CAPACIDAD) VALUES (1,10);
INSERT INTO DESPACHOS (NUMERO, CAPACIDAD) VALUES (2,15);
INSERT INTO DESPACHOS (NUMERO, CAPACIDAD) VALUES (3,20);
INSERT INTO DESPACHOS (NUMERO, CAPACIDAD) VALUES (4,25);
INSERT INTO DESPACHOS (NUMERO, CAPACIDAD) VALUES (5,30);
INSERT INTO DESPACHOS (NUMERO, CAPACIDAD) VALUES (6,35);
INSERT INTO DESPACHOS (NUMERO, CAPACIDAD) VALUES (7,40);
INSERT INTO DESPACHOS (NUMERO, CAPACIDAD) VALUES (8,45);
INSERT INTO DESPACHOS (NUMERO, CAPACIDAD) VALUES (9,50);
INSERT INTO DESPACHOS (NUMERO, CAPACIDAD) VALUES (10,55);
INSERT INTO DESPACHOS (NUMERO, CAPACIDAD) VALUES (11,60);
/* INSERT TABLA DIRECTORES */
INSERT INTO DIRECTORES (DNI, NOMBREAPELLIDOS, FK_DNIJEFE,FK_DESPACHO) VALUES ('4800000X', 'JOSUE', '4800000X', 1);
INSERT INTO DIRECTORES (DNI, NOMBREAPELLIDOS, FK_DNIJEFE,FK_DESPACHO) VALUES ('5500516S', 'PACO', '5500516S', 2);
INSERT INTO DIRECTORES (DNI, NOMBREAPELLIDOS, FK_DNIJEFE,FK_DESPACHO) VALUES ('6184948A', 'FEDE', '5500516S', 2);
INSERT INTO DIRECTORES (DNI, NOMBREAPELLIDOS, FK_DNIJEFE,FK_DESPACHO) VALUES ('1616165B', 'TUPU', '5500516S', 2);
INSERT INTO DIRECTORES (DNI, NOMBREAPELLIDOS, FK_DNIJEFE,FK_DESPACHO) VALUES ('6164164K', 'MENDIETA', '5500516S', 2);
INSERT INTO DIRECTORES (DNI, NOMBREAPELLIDOS, FK_DNIJEFE,FK_DESPACHO) VALUES ('3646465F', 'MARDONA', '4800000X', 1);
INSERT INTO DIRECTORES (DNI, NOMBREAPELLIDOS, FK_DNIJEFE,FK_DESPACHO) VALUES ('6118898L', 'JOZE', '6118898L', 3);
INSERT INTO DIRECTORES (DNI, NOMBREAPELLIDOS, FK_DNIJEFE,FK_DESPACHO) VALUES ('2655466Ñ', 'MARIA', '6118898L', 3);
INSERT INTO DIRECTORES (DNI, NOMBREAPELLIDOS, FK_DNIJEFE,FK_DESPACHO) VALUES ('1561566A', 'JOSEFA', '6118898L', 3);
INSERT INTO DIRECTORES (DNI, NOMBREAPELLIDOS, FK_DNIJEFE,FK_DESPACHO) VALUES ('1468948V', 'ANA', '6118898L', 3);
INSERT INTO DIRECTORES (DNI, NOMBREAPELLIDOS, FK_DNIJEFE,FK_DESPACHO) VALUES ('4516166Q', 'CLAUDIA', '4800000X', 1);
/* TUPLA DE ERROR , TODO OK */
INSERT INTO DIRECTORES (DNI, NOMBREAPELLIDOS, FK_DNIJEFE,FK_DESPACHO) VALUES ('66464894P', 'OCTAVIO', '000', 1);
SELECT * FROM DIRECTORES;
SELECT * FROM DESPACHOS;